++++++++++          (Set cell 0 to 10: loop counter)
[                   (Start loop)
    > +++++++       (Add 7 to cell 1)
    > ++++++++++    (Add 10 to cell 2)
    > +++           (Add 3 to cell 3)
    > +             (Add 1 to cell 4)
    <<<< -          (Return to cell 0 and decrement by 1)
]                   (Loop until cell 0 becomes 0)

> ++ .              (Cell 1: 70 + 2 = 72  -> Output 'H')
> + .               (Cell 2: 100 + 1 = 101 -> Output 'e')
+++++++ .           (Cell 2: 101 + 7 = 108 -> Output 'l')
.                   (Cell 2: remains 108   -> Output 'l')
+++ .               (Cell 2: 108 + 3 = 111 -> Output 'o')
> ++ .              (Cell 3: 30 + 2 = 32   -> Output ' ' [space])
> .                 (Cell 4: remains 10    -> Output '\n' [newline])
